import{deliverAlert}from"./alert-store";
const endpoint=process.env.SUPABASE_URL?.replace(/\/$/,""),key=process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY;
async function db(path:string,init?:RequestInit){if(!endpoint||!key)throw new Error("Monitor database is not configured.");const r=await fetch(`${endpoint}/rest/v1/${path}`,{...init,headers:{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",Prefer:"return=representation",...(init?.headers||{})},cache:"no-store"});if(!r.ok)throw new Error(`Monitor database error (${r.status})`);const t=await r.text();return t?JSON.parse(t):null;}
const wait=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function history(address:string){const k=process.env.HELIUS_API_KEY?.trim();if(!k)throw new Error("Helius is not configured.");const u=`https://api.helius.xyz/v0/addresses/${encodeURIComponent(address)}/transactions?api-key=${encodeURIComponent(k)}&limit=12`;for(let i=0;i<3;i++){const r=await fetch(u,{cache:"no-store"});if(r.ok)return await r.json();if((r.status===429||r.status>=500)&&i<2){await wait(500*2**i);continue}throw new Error(`Helius monitor failed (${r.status})`)}return[]}
function classify(x:any){const s=`${x?.type||""} ${x?.description||""}`;if(/TOKEN_MINT|CREATE|INITIALIZE|MINT/i.test(s))return{kind:"launch_signal",title:"New launch signal",body:String(x?.description||"New token-creation activity was observed.")};if(/SWAP/i.test(s))return{kind:"swap_activity",title:"New swap activity",body:String(x?.description||"New swap activity was observed.")};if(/TRANSFER/i.test(s))return{kind:"transfer_activity",title:"New transfer activity",body:String(x?.description||"New transfer activity was observed.")};return{kind:"wallet_activity",title:"New wallet activity",body:String(x?.description||x?.type||"New on-chain activity was observed.")}}
async function state(watchId:string){const r=await db(`rugprint_watch_state?watch_id=eq.${watchId}&select=*`);return r?.[0]||null}
async function save(watchId:string,p:any){await db("rugprint_watch_state?on_conflict=watch_id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({watch_id:watchId,...p,updated_at:new Date().toISOString()})})}
async function monitorOne(w:any){if(!["wallet","contract"].includes(w.watch_type))return{watchId:w.id,status:"waiting_for_identity_link"};try{const txs=await history(String(w.watch_value));const newest=txs?.[0];if(!newest?.signature){await save(w.id,{last_checked_at:new Date().toISOString(),last_error:null});return{watchId:w.id,status:"no_activity"}}const s=await state(w.id);if(!s?.baseline_ready){await save(w.id,{last_signature:newest.signature,last_checked_at:new Date().toISOString(),baseline_ready:true,last_error:null});return{watchId:w.id,status:"baseline_created"}}if(s.last_signature===newest.signature){await save(w.id,{last_checked_at:new Date().toISOString(),last_error:null});return{watchId:w.id,status:"unchanged"}}
const oldIndex=txs.findIndex((x:any)=>x.signature===s.last_signature);const fresh=(oldIndex<0?txs.slice(0,1):txs.slice(0,oldIndex)).reverse();let delivered=0;for(const tx of fresh.slice(-3)){const c=classify(tx);const result=await deliverAlert(w.subscription_id,c.kind,c.title,`${c.body}\n\nWatched ${w.watch_type}: ${w.watch_value}`,w.id);if(result.delivered)delivered++}
await save(w.id,{last_signature:newest.signature,last_checked_at:new Date().toISOString(),last_error:null});return{watchId:w.id,status:"updated",delivered}}catch(e){const msg=e instanceof Error?e.message:"monitor_failed";await save(w.id,{last_checked_at:new Date().toISOString(),last_error:msg}).catch(()=>null);return{watchId:w.id,status:"error",error:msg}}}
export async function runWatchMonitor(){const watches=await db("rugprint_alert_watches?enabled=eq.true&select=id,subscription_id,watch_type,watch_value&order=created_at.asc&limit=250");const results=[];for(const w of watches||[]){results.push(await monitorOne(w));await wait(120)}return{checked:results.length,results,at:new Date().toISOString()}}
